// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9w3gam3Ab2ZnxieiVTMpRsIlqVkiZ9N0',
    appId: '1:98994414210:web:f5d3ed4ed51b4873d80a9b',
    messagingSenderId: '98994414210',
    projectId: 'ratewings',
    authDomain: 'ratewings.firebaseapp.com',
    databaseURL: 'https://ratewings.firebaseio.com',
    storageBucket: 'ratewings.appspot.com',
    measurementId: 'G-5JP0470JY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKuqCzAoJYre5lXJWDfsbN-61pvoquPXU',
    appId: '1:98994414210:android:5f4377de7504cdfbd80a9b',
    messagingSenderId: '98994414210',
    projectId: 'ratewings',
    databaseURL: 'https://ratewings.firebaseio.com',
    storageBucket: 'ratewings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCni-DyX8qAEymuBCR_eorzy4KrSkkHZ7o',
    appId: '1:98994414210:ios:bcacf3b1c9f18dffd80a9b',
    messagingSenderId: '98994414210',
    projectId: 'ratewings',
    databaseURL: 'https://ratewings.firebaseio.com',
    storageBucket: 'ratewings.appspot.com',
    iosClientId: '98994414210-1v72vmoe11daph1tol10s7m7n1sh8p41.apps.googleusercontent.com',
    iosBundleId: 'com.mampersat.ratewings.ratewings',
  );
}
